# Generated by Django 2.2.1 on 2019-05-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190519_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='font',
            field=models.CharField(default='rgb(253, 246, 227)', max_length=50),
        ),
    ]
