# Generated by Django 2.2.1 on 2019-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_tag_font'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='potion_quantity',
            new_name='portion_quantity',
        ),
        migrations.AlterField(
            model_name='tag',
            name='font',
            field=models.CharField(default='rgb(253, 246, 227)', editable=False, max_length=50),
        ),
    ]
