# Generated by Django 2.2.1 on 2019-05-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20190520_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='order_group',
        ),
    ]
