# Generated by Django 2.2.1 on 2019-06-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20190616_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='public_slug',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
