# Generated by Django 2.2.1 on 2019-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20190616_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='public_slug',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
