# Generated by Django 2.2.1 on 2019-10-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20190831_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_tmb'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
