# Generated by Django 2.2.1 on 2019-10-09 15:30

from django.db import migrations


def make_thumbnails(apps, schema_editor):
    from recipes.models import Picture
    for picture in Picture.objects.all():
        image = picture.image
        name = image.name.split('/')[-1]
        picture.thumbnail = picture.make_thumbnail(image.file)
        picture.thumbnail.name = name
        picture.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20191009_1729'),
    ]

    operations = [
        migrations.RunPython(make_thumbnails)
    ]
