# Generated by Django 2.2.1 on 2019-10-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20191009_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='recipes_tmb'),
        ),
    ]
