# Generated by Django 2.2.25 on 2024-06-02 21:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20191009_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='direction',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='recipes_dir_search__b9626c_gin'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='recipes_ing_search__a4b806_gin'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='recipes_rec_search__ce256b_gin'),
        ),
    ]
